export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_REDUCER = 'CHANGE_REDUCER';
export const ADD_REDUCER = 'ADD_REDUCER';
export const REMOVE_REDUCER = 'REMOVE_REDUCER';
export const CHANGE_PORT = 'CHANGE_PORT'; 
export const TOGGLE_EXPRESS_CATEGORY = 'TOGGLE_EXPRESS_CATEGORY';
export const TOGGLE_REDUX_CATEGORY = 'TOGGLE_REDUX_CATEGORY';
export const TOGGLE_REACT_ROUTER_CATEGORY = 'TOGGLE_REACT_ROUTER_CATEGORY';
export const TOGGLE_WEBPACK_CATEGORY = 'TOGGLE_WEBPACK_CATEGORY';

export const TOGGLE_EXPRESS_MIDDLEWARE = 'TOGGLE_EXPRESS_MIDDLEWARE';

// Static Middleware

export const CHANGE_PATH = 'CHANGE_PATH';
export const ADD_PATH = 'ADD_PATH';
export const REMOVE_PATH = 'REMOVE_PATH';

// Body Parser = JSON

export const TOGGLE_BPJ_OPTION = 'TOGGLE_BPJ_OPTION'; 

export const CODE_GENERATED = 'CODE_GENERATED';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const CHANGE_RESOURCE_NAME = 'CHANGE_RESOURCE_NAME';

// Resource Actions

export const TOGGLE_RESOURCE_EXPRESS = 'TOGGLE_RESOURCE_EXPRESS';
export const TOGGLE_RESORCE_REACT_ROUTER = 'TOGGLE_RESORCE_REACT_ROUTER'; 
export const TOGGLE_RESOURCE_CONTAINER = 'TOGGLE_RESOURCE_CONTAINER';
export const TOGGLE_RESOURCE_REDUCER = 'TOGGLE_RESOURCE_REDUCER';
export const TOGGLE_RESOURCE_OPTION = 'TOGGLE_RESOURCE_OPTION';