export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_REDUCER = 'CHANGE_REDUCER';
export const ADD_REDUCER = 'ADD_REDUCER';
export const REMOVE_REDUCER = 'REMOVE_REDUCER';
export const CHANGE_PORT = 'CHANGE_PORT'; 
export const TOGGLE_EXPRESS_CATEGORY = 'TOGGLE_EXPRESS_CATEGORY';
export const TOGGLE_REDUX_CATEGORY = 'TOGGLE_REDUX_CATEGORY';

export const TOGGLE_EXPRESS_MIDDLEWARE = 'TOGGLE_EXPRESS_MIDDLEWARE';

// Static Middleware

export const CHANGE_PATH = 'CHANGE_PATH';
export const ADD_PATH = 'ADD_PATH';
export const REMOVE_PATH = 'REMOVE_PATH';

// Body Parser = JSON

export const TOGGLE_BPJ_OPTION = 'TOGGLE_BPJ_OPTION'; 

export const CODE_GENERATED = 'CODE_GENERATED';